Processing module test19 (test_input/test19.py)...

Warnings...

test_input/test19.py:8: Invalid arguments to (__init__), got 2, expected between 0 and 1
test_input/test19.py:9: Invalid arguments to (__init__), got 3, expected between 0 and 1
